#!/bin/sh /etc/rc.common
# chimera-rawmodem: serial<->TCP bridge (must start before digipeater/igate)
# Install: copy to /etc/init.d/chimera-bridge, chmod +x, /etc/init.d/chimera-bridge enable

START=90
USE_PROCD=1

PROG=/usr/bin/chimera-bridge.py
CONF=/etc/chimera/config.yaml

start_service() {
	procd_open_instance
	procd_set_param command /usr/bin/python "$PROG" "$CONF"
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
